### ISSUE TITLE
TweenLite.delayedCall argument issues

### ISSUE THREAD

**Issue by ghost** [mathieuanthoine/haxe-gsap#3]
Hello there

I noticed that the `callback` argument to `TweenLite.delayedCall` is typed `Void->Void`.  However, we clearly want to be able to supply a callback that might accept any number of arguments, that will be passed the contents of the optional `params` array. As also explained in the [GSAP documentation](https://greensock.com/docs/#/HTML5/GSAP/TweenLite/delayedCall/).

[Here](https://github.com/mathieuanthoine/haxe-gsap/blob/master/src/com/greensock/TweenLite.hx#L70) is the relevant line.

For the time being I have replaced

`TweenLite.delayedCall( delay, myCallback, [a,b,c])`   

with

`TweenLite.delayedCall( delay, myCallback.bind(a,b,c))`  

so that the types match. Do you think there is a good fix for this?  Obviously it depends a great deal on how the callback is evoked by the underlying GSAP library. 

Thoughts? 
-colin

**Comment by mathieuanthoine** [comment]
Hi,

Try to modify your local externs with Dynamic as type for myCallBack. If it works, thank you to PR :)
